// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import ()

type Account struct {
	ID      int64
	Address string
	Balance int64
}

type Tx struct {
	ID     string
	Payer  string
	Payee  string
	Amount int64
	TxHash string
	Sig    string
}
