// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type Account struct {
	ID      int64
	Address string
	Balance int64
}

type Tx struct {
	ID     string
	Height int64
	Payer  string
	Payee  string
	Amount int64
}
