// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type Account struct {
	Address string `json:"address"`
	Balance int64  `json:"balance"`
}

type Tx struct {
	Height int64  `json:"height"`
	Payer  string `json:"payer"`
	Payee  string `json:"payee"`
	Amount int64  `json:"amount"`
}
