# fly.toml app configuration file generated for gogo-webauthn on 2023-09-27T22:55:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gogo-webauthn"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[env]
  PORT = "8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
